### ISSUE TITLE
Use pip-service instead of wof-admin-lookup

### ISSUE THREAD

**Issue by tadjik1** [pelias/openstreetmap#345]
Hi there.

Currently this importer uses `wof-admin-lookup` module for getting hierarchy which means that you have to have all required who's on first data in the same machine. Of course you can mount folder with data using something like EFS or so, but it requires some additional steps.

One possible solution for this could be using `pip-service` in all places that require admin lookup. So that data will be stored only in one place and always will be reachable by HTTP which is slower than direct fs access but much more agnostic.

**Comment by orangejulius** [comment]
Hey @tadjik1,
Yes! This is something we've wanted to do for a long time. The PIP service already internally uses all the same code and data, and we previously did have HTTP support within `wof-admin-lookup`.

Surprisingly there wasn't a top level ticket to track this, and since it would affect all the importers, not just openstretmap, I've made https://github.com/pelias/wof-admin-lookup/issues/160 to track it, and I'm going to close this issue to keep this repo's issue list clean. 

This is something we want to work on very soon. If you want to try to get us closer we'd also be happy to help you get started.
