### ISSUE TITLE
Multi-thread importation?

### ISSUE THREAD

**Issue by Binternet** [pelias/openstreetmap#402]
Is there a way to run osm importer as a multi-thread process and by that making the import process faster?

**Comment by orangejulius** [comment]
Node.js does not support multi-threading for user code, so in general no. Part of this repo uses the Go [pbf2json](https://github.com/pelias/pbf2json) utility, which _is_ multi-threaded and you should see it use considerable CPU during long imports.

Furthermore, unlike the [OpenAddresses](https://github.com/pelias/openaddresses/) which can process many different files in parallel, there's no easy way to split the work of importing a full planet OSM extract, so it has to be done in a single process.

The main thing slowing the OSM import down is actually the [point in polygon service](https://github.com/pelias/pip-service) and the JSON parsing/seralization that happens when communicating it.

Some things we are looking at, and would love help with if you have the time, to speed up the imports are:
* experiment with minimizing the amount of JSON we send between the importers and the PIP service. Less JSON = less time spent parsing/serializing
* Switch the PIP service from Express to [Fastify](https://www.fastify.io/) which is supposed to be quite a bit faster for this particular case
* (longer term) rewrite the PIP service in go, so that it can be multi-threaded (As it loads lots of data into memory, it's not efficient to have multiple copies of the service in order to increase capacity)

Finally, one practical change you can make today to slightly speed things up is use the highest Node.js version you can. I've tested most of our code on Node.js 9 and even Node.js 10 nightly builds, and they are the fastest. At the very least use Node.js 8.

**Comment by Binternet** [comment]
Hey @orangejulius sorry I did not response for this issue.

Unfortunately i'm not that experienced with node so I cannot make any code offerings and improvements, I do have linux/aws/php knowledge and I am examining Pelias as a full-planet intended for heavy production usage, so you whatever I can do to help support this great project - i will do my best.

**Comment by orangejulius** [comment]
Hey @Binternet,
No worries. I did not expect a response here but was cleaning up issues that don't have any action left on our part to take. I hope the full build adventures are going well. And at the risk of a shameless plug, let us know over at clearedfortakeoff.co if you want help setting up Pelias specifically for your needs more efficiently than we can offer via github issues :)

**Comment by Binternet** [comment]
Just pinged you =)

**Comment by jeremy-rutman** [comment]
I don't know if solves the problem of parallel osm importation for pelias (i'm not at all familiar with node), but I have worked in parallel on planet.osm after splitting it by outermost xml tag into a few hundred files and working on those in parallel.

**Comment by stefanocudini** [comment]
> The main thing slowing the OSM import down is actually the [point in polygon service](https://github.com/pelias/pip-service) and the JSON parsing/seralization that happens when communicating it.

@orangejulius  you might take this into consideration this solution:
https://github.com/fastify/fluent-json-schema
