### ISSUE TITLE
Wrong neighborhood listed for this OSM way

### ISSUE THREAD

**Issue by stevevance** [pelias/openstreetmap#79]
http://www.openstreetmap.org/way/210679250
Urban Outfitters returns with neighborhood "Gold Cost" but it should say "Gold Coast". The search query for the Pelias API I used was http://pelias.mapzen.com/search?input=urban%20remains&lat=41.809148&lon=-87.618538&bbox=-88.30,41.430,-87.47,42.198&layers=poi,address

**Comment by missinglink** [comment]
thanks for the report @stevevance, I have forwarded it to our data team.

if you haven't seen it yet we have an exciting new project in the works at mapzen called [who's on first](https://mapzen.com/blog/who-s-on-first) which will provide a much better source of open polygon data to the geo community.

that project isn't quite ready for integration in to Pelias but when the time comes we will be upgrading to it

**Comment by missinglink** [comment]
oh also a little off topic @stevevance but we are working on an API redesign at the moment which will break backwards compatibility, the estimates at this stage are to roll out the new API in the next few weeks and then aim to fully deprecate the current API ~1 month after that.

we are going to do this in a controlled fashion and (if you have an API key) you'll get an email explaining how it's going to work, time-frames etc.

if you haven't signed up for a Pelias API key for your projects then now is the time to do so, it will ensure that we can track who is using the old API in order to avoid breaking 3rd party integrations.

**Comment by missinglink** [comment]
thanks again @stevevance, I can see the data team has made the correction in the WOF dataset so I'm going to close this issue now.

We are no longer patching the quattroshapes data so unfortunately you won't see this change in the production environment until we switch from quattroshapes to WOF.

**Comment by stevevance** [comment]
@missinglink Will I have to do anything when you switch from quattroshapes to WOF? I don't believe they're specifiable as layers, so I believe the answer is "no".

**Comment by riordan** [comment]
Precisely. It will switch over to using the Who's on First data
automatically.

On Fri, Sep 25, 2015 at 2:10 PM, Steven Vance <notifications@github.com>
wrote:

> @missinglink <https://github.com/missinglink> Will I have to do anything
> when you switch from quattroshapes to WOF? I don't believe they're
> specifiable as layers, so I believe the answer is "no".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/openstreetmap/issues/79#issuecomment-143311215>
> .
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>
