### ISSUE TITLE
insert data in ES

### ISSUE THREAD

**Issue by harksin** [pelias/openstreetmap#88]
hi, 

I trying to import osm data for mys city (pbf file) in ES. 

i have a custom config file with only OSM.

when i execute "node index.js" i catch the following error.

```
2016-01-15T18:06:01.105Z - info: [admin-lookup:master] Initializing workers.
2016-01-15T18:06:01.259Z - info: [admin-lookup:worker:admin1] Loading `admin1`.
ShapeFileStream { [Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_adm1.dbf']
  errno: -2,
  code: 'ENOENT',
  path: '/mnt/pelias/quattroshapes/qs_adm1.dbf' }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_adm1.dbf'
    at Error (native)
2016-01-15T18:06:01.290Z - info: [admin-lookup:worker:locality] Loading `locality`.
2016-01-15T18:06:01.296Z - info: [admin-lookup:worker:local_admin] Loading `local_admin`.
ShapeFileStream { [Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_localities.dbf']
  errno: -2,
  code: 'ENOENT',
  path: '/mnt/pelias/quattroshapes/qs_localities.dbf' }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_localities.dbf'
    at Error (native)
ShapeFileStream { [Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_localadmin.dbf']
  errno: -2,
  code: 'ENOENT',
  path: '/mnt/pelias/quattroshapes/qs_localadmin.dbf' }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_localadmin.dbf'
    at Error (native)
2016-01-15T18:06:01.317Z - info: [admin-lookup:worker:admin2] Loading `admin2`.
ShapeFileStream { [Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_adm2.dbf']
  errno: -2,
  code: 'ENOENT',
  path: '/mnt/pelias/quattroshapes/qs_adm2.dbf' }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_adm2.dbf'
    at Error (native)
2016-01-15T18:06:01.343Z - info: [admin-lookup:worker:neighborhood] Loading `neighborhood`.
ShapeFileStream { [Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_neighborhoods.dbf']
  errno: -2,
  code: 'ENOENT',
  path: '/mnt/pelias/quattroshapes/qs_neighborhoods.dbf' }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/mnt/pelias/quattroshapes/qs_neighborhoods.dbf'
    at Error (native)

```

Do you have seen this error before ?
And could you help me to solve them ?

thanks a lots for your great works.

harksin.

**Comment by orangejulius** [comment]
hey @harksin,
This error is the importer telling you it can't find the data files for [Quattroshapes](http://quattroshapes.mapzen.com/). While you're importing OSM, the data files for Quattroshapes are used to make sure all the imported records have values set for country, city, etc, since many OSM records don't have those.

You can fix this in one of two ways:
1.) Filling in these values (we call it admn lookup) can be disabled, and then quattroshapes isn't needed. Find the openstreetmap section of your openstreetmap config, and set `"adminLookup": false`.
2.) Download the `quattroshapes-simplified.tar.gz` from the link above (it's about 500MB), and configure your pelias config with the path to where you put these files (it looks like you've still got it set to the default). You can see a very simple example [here](https://github.com/pelias/config/blob/master/config/local.json).

Let me know if that works, enjoy!

**Comment by harksin** [comment]
@orangejulius  thanks! It works fine now =)!!

Just 2 quick question : 
- there is a parameter to specify the  pelias.json  path ?
- did you plan to provide pelias as docker container ?

**Comment by orangejulius** [comment]
Glad it all works for you!

You can specifiy `PELIAS_CONFIG=/path/to/your/pelias.json` as an environmental variable before any of the importer commands, or use `export PELIAS_CONFIG=...` in your shell (or even in a settings file like `.bashrc`) to make more permanent changes.

We don't have any plans for docker containers at the moment but it's probably something we will look at eventually.

P.S. Looks like we've solved your issue so I'm closing this ticket. Feel free to ask us more questions.
